### ISSUE TITLE
Test example not working on VPN

### ISSUE THREAD

**Issue by rzinke** [isofit/isofit#216]
I have cloned the repo from github and carried out the installation instructions (i.e., ```pip install --editable /Users/rzinke/Tools/isofit/ --use-feature=2020-resolver```).

I am now trying to run a quickstart example using MODTRAN 6.0. I cd to ```examples/20171108_Pasadena/```, and run ```./run_example_modtran.sh```

When I do this, however, I get the following error message.

```
Configuration file checks complete, no errors found.
Automatically increasing RLIMIT_NOFILE to max value of 9223372036854775807
Failed to raise limit.
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
Traceback (most recent call last):
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rzinke/opt/miniconda3/envs/isofit/bin/isofit", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/rzinke/Tools/isofit/bin/isofit", line 54, in <module>
    main()
  File "/Users/rzinke/Tools/isofit/bin/isofit", line 47, in main
    isofit = Isofit(config_file=config, level=level, row_column=row_column)
  File "/Users/rzinke/Tools/isofit/isofit/core/isofit.py", line 96, in __init__
    ray.init(**rayargs)
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/ray/worker.py", line 718, in init
    ray_params=ray_params)
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/ray/node.py", line 220, in __init__
    self.start_head_processes()
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/ray/node.py", line 827, in start_head_processes
    self.start_redis()
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/ray/node.py", line 642, in start_redis
    fate_share=self.kernel_fate_share)
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/ray/_private/services.py", line 852, in start_redis
    primary_redis_client.set("NumRedisShards", str(num_redis_shards))
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 60 connecting to 137.79.233.143:6379. Operation timed out.
./run_example_modtran.sh: line 13: 71658 Terminated: 15          isofit --level DEBUG configs/ang20171108t184227_beckmanlawn-undersmoothed.json
```

**Comment by rzinke** [comment]
@davidraythompson suggested this was a problem with my VPN preventing the ray parallelization scheme from communicating with its server.

I logged out of my JPL VPN. Now the example appears to have worked, however, I get many "DEBUG" messages printed to my screen.

```
(pid=15728) DEBUG:findfont: score(<Font 'Serto Jerusalem' (SyrCOMJerusalem.otf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'Hoefler Text' (Hoefler Text Ornaments.ttf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'STIXIntegralsUpD' (STIXIntUpDReg.otf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'DIN Condensed' (DIN Condensed Bold.ttf) normal normal 700 condensed>) = 10.535
(pid=15728) DEBUG:findfont: score(<Font '.SF Compact Display' (SFCompactDisplay-Semibold.otf) normal normal 600 normal>) = 10.24
(pid=15728) DEBUG:findfont: score(<Font '.SF NS Display Condensed' (SFNSDisplayCondensed-Semibold.otf) normal normal 700 condensed>) = 10.535
(pid=15728) DEBUG:findfont: score(<Font 'East Syriac Adiabene' (SyrCOMAdiabene.otf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'Zapf Dingbats' (ZapfDingbats.ttf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'Bitstream Vera Sans Mono' (VeraMono.ttf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font '.SF Compact Display' (SFCompactDisplay-Bold.otf) normal normal 700 normal>) = 10.335
(pid=15728) DEBUG:findfont: score(<Font '.Arabic UI Display' (ArabicUIDisplay.ttc) normal normal 900 normal>) = 10.525
(pid=15728) DEBUG:findfont: score(<Font 'Estrangelo Edessa' (SyrCOMEdessa.otf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'Hiragino Sans' (ヒラギノ角ゴシック W4.ttc) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font '.SF NS Rounded' (SFNSRounded.ttf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'System Font' (SFNSDisplay-LightItalic.otf) italic normal 300 normal>) = 11.145
(pid=15728) DEBUG:findfont: score(<Font '.SF NS Display Condensed' (SFNSDisplayCondensed-Regular.otf) normal normal 600 condensed>) = 10.44
(pid=15728) DEBUG:findfont: score(<Font 'AppleGothic' (AppleGothic.ttf) normal normal 400 normal>) = 10.05
(pid=15728) DEBUG:findfont: score(<Font 'STIXIntegralsSm' (STIXIntSmBol.otf) normal normal 700 normal>) = 10.335
(pid=15728) DEBUG:findfont: Matching sans\-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/Users/rzinke/opt/miniconda3/envs/isofit/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
Inversions complete.  12.81 s total, 0.078 spectra/s, 0.078 spectra/s/core
```

These are non-fatal, and the inversion process appears to have completed successfully. Thanks!

**Comment by pgbrodrick** [comment]
Glad that the terminating the VPN resolved the core challenge (I've seen that before as well, and we'll keep looking into ways to circumvent).  For the debug messages...at first glance these look like they might be from plotting.  Can you turn off the figure generation (remove "plot_directory" from the config file - underneath "output")  in the Pasadena example and see if those messages persist?

**Comment by rzinke** [comment]
Thanks @pgbrodrick. It appears that those were indeed related to the plotting feature. Removing them from the configuration files leads to this output:

```
Configuration file checks complete, no errors found.
Automatically increasing RLIMIT_NOFILE to max value of 9223372036854775807
Failed to raise limit.
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
2021-03-10 08:35:12,352	INFO services.py:1174 -- View the Ray dashboard at http://127.0.0.1:8265
Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/remote/ang20171108t184227_rdn_v2p11_BeckmanLawn.txt
Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/insitu/BeckmanLawn.txt
Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/output/ang20171108t184227_alg_v2p11_BeckmanLawn-undersmoothed.txt
Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/output/ang20171108t184227_rfl_v2p11_BeckmanLawn-undersmoothed.txt
Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/output/ang20171108t184227_mdl_v2p11_BeckmanLawn-undersmoothed.txt
Beginning inversions using 1 cores
(pid=36107) DEBUG:Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/remote/ang20171108t184227_rdn_v2p11_BeckmanLawn.txt
(pid=36107) DEBUG:Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/insitu/BeckmanLawn.txt
(pid=36107) DEBUG:Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/output/ang20171108t184227_alg_v2p11_BeckmanLawn-undersmoothed.txt
(pid=36107) DEBUG:Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/output/ang20171108t184227_rfl_v2p11_BeckmanLawn-undersmoothed.txt
(pid=36107) DEBUG:Inferred ASCII file format for /Users/rzinke/Tools/isofit/examples/20171108_Pasadena/output/ang20171108t184227_mdl_v2p11_BeckmanLawn-undersmoothed.txt
(pid=36107) DEBUG:Row 0 Column 0
(pid=36107) DEBUG:Iteration: 01  Residual:     20405.61 Component: 6 Atmosphere: AOT550: 0.050 H2OSTR: 1.876 
(pid=36107) DEBUG:Iteration: 02  Residual:      3203.15 Component: 6 Atmosphere: AOT550: 0.049 H2OSTR: 1.884 
(pid=36107) DEBUG:Iteration: 03  Residual:      1073.11 Component: 6 Atmosphere: AOT550: 0.049 H2OSTR: 1.888 
(pid=36107) DEBUG:Iteration: 04  Residual:       653.23 Component: 6 Atmosphere: AOT550: 0.049 H2OSTR: 1.891 
(pid=36107) DEBUG:Iteration: 05  Residual:       579.73 Component: 6 Atmosphere: AOT550: 0.049 H2OSTR: 1.894 
(pid=36107) DEBUG:Iteration: 06  Residual:       554.06 Component: 6 Atmosphere: AOT550: 0.048 H2OSTR: 1.896 
(pid=36107) DEBUG:Iteration: 07  Residual:       526.33 Component: 6 Atmosphere: AOT550: 0.046 H2OSTR: 1.905 
(pid=36107) DEBUG:Iteration: 08  Residual:       522.40 Component: 6 Atmosphere: AOT550: 0.046 H2OSTR: 1.906 
(pid=36107) DEBUG:IO: Writing algebraic_inverse_file
(pid=36107) DEBUG:IO: Writing estimated_reflectance_file
(pid=36107) DEBUG:IO: Writing modeled_radiance_file
(pid=36107) DEBUG:IO: Writing data_dump_file
Inversions complete.  9.84 s total, 0.1016 spectra/s, 0.1016 spectra/s/core
```

The inversions completed successfully.

**Comment by pgbrodrick** [comment]
Closing this out, as it seems to be resolved!  Please re-open as needed.
