### ISSUE TITLE
User wavelength file consistency checking

### ISSUE THREAD

**Issue by davidraythompson** [isofit/isofit#323]
I made a silly user error, making a high resolution radiative transfer wavelengths file that did not span the full range of the instrument wavelengths file.  This generated a cryptic error message.  I'm reporting it in case we want to capture this kind of problem in our input file consistency checking.

Traceback (most recent call last):
  File "/home/drt/src/isofit/bin/isofit", line 52, in <module>
    main()
  File "/home/drt/src/isofit/bin/isofit", line 47, in main
    return isofit.run()
  File "/home/drt/src/isofit/isofit/core/isofit.py", line 164, in run
    res = list(self.workers.map_unordered(lambda a, b: a.run_set_of_spectra.remote(b), indices_to_run))
  File "/home/drt/src/anaconda3/lib/python3.7/site-packages/ray/util/actor_pool.py", line 93, in map_unordered
    yield self.get_next_unordered()
  File "/home/drt/src/anaconda3/lib/python3.7/site-packages/ray/util/actor_pool.py", line 216, in get_next_unordered
    return ray.get(future)
  File "/home/drt/src/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/drt/src/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1713, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::Worker.run_set_of_spectra() (pid=121928, ip=172.16.0.2, repr=<isofit.core.isofit.Worker object at 0x7f36f65983d0>)
  File "/home/drt/src/isofit/isofit/core/isofit.py", line 225, in run_set_of_spectra
    states = self.iv.invert(input_data.meas, input_data.geom)
  File "/home/drt/src/isofit/isofit/inversion/inverse.py", line 328, in invert
    Seps_inv, Seps_inv_sqrt = self.calc_Seps(x, meas, geom)
  File "/home/drt/src/isofit/isofit/inversion/inverse.py", line 180, in calc_Seps
    Seps = self.fm.Seps(x, meas, geom)
  File "/home/drt/src/isofit/isofit/core/forward.py", line 224, in Seps
    Kb = self.Kb(x, geom)
  File "/home/drt/src/isofit/isofit/core/forward.py", line 289, in Kb
    drdn_dRTb.T).T
  File "/home/drt/src/isofit/isofit/core/instrument.py", line 263, in sample
    resamp.append(interp1d(wl_hi, blur)(wl))
  File "/home/drt/src/anaconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "/home/drt/src/anaconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 663, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/home/drt/src/anaconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 692, in _check_bounds
    raise ValueError("A value in x_new is below the interpolation "
ValueError: A value in x_new is below the interpolation range.

**Comment by pgbrodrick** [comment]
Thanks for reporting!  Let's take a look at this specific issue, but also add an action item to check wavelength consistency in the config file early on and report a user-friendly error if adjustments are likely.
