### ISSUE TITLE
Ray OOM errors with analytical line in apply_oe

### ISSUE THREAD

**Issue by NickVaughn** [isofit/isofit#462]
When running apply_oe on a full flight line, unless I request an insane amount of memory (300Gb+) in a slurm task, I cannot run analytical line inversion.

Output shows a good number of these warnings:
```2024-02-28 19:42:27,665 WARNING worker.py:2058 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: 72797b649933a7a8b5bb64da72e7e4cad6b2487901000000 Worker ID: e47ff8984e3677481949634bcbc514db23d9736814e04feda0f66449 Node ID: f28880fe2dcf01907eebda9048bd6fb20c0538f0163d924941c6aeb1 Worker IP address: 10.139.121.107 Worker port: 39753 Worker PID: 3414402 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
...
Many of these warnings, leading to a fail of the interpolation and an unsuccessful completion of apply_oe. Final backtrace looks like this:
Traceback (most recent call last):
  File "/home/nvaughn4/repos/isofit/isofit/utils/apply_oe.py", line 2001, in <module>
    _cli()
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/nvaughn4/repos/isofit/isofit/utils/apply_oe.py", line 1995, in _cli
    apply_oe(SimpleNamespace(**kwargs))
  File "/home/nvaughn4/repos/isofit/isofit/utils/apply_oe.py", line 556, in apply_oe
    analytical_line(
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/isofit/utils/analytical_line.py", line 104, in analytical_line
    atm_interpolation(
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/isofit/utils/atm_interpolation.py", line 341, in atm_interpolation
    _ = ray.get(results)
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/nvaughn4/miniconda3/envs/isofit_env/lib/python3.10/site-packages/ray/_private/worker.py", line 2549, in get
    raise value
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
slurmstepd: error: Detected 48 oom_kill events in StepId=13960973.batch. Some of the step tasks have been OOM Killed.
```

This is with even a relatively low number of cores, like 5 and reasonable amount of memory ~120Gb. I have 0 issues empirical line mode with more cores and much less memory.

This has been for several revisions of the main and dev branches. I haven't pulled recently because we're in production mode right now and I don't want to mess with what's working.

I was thinking it was all my environment like a bad version of Ray, but I've tested on multiple versions of this library and several others. I saw that similar issues were fixed for the LUT computations in a recent pull request: https://github.com/isofit/isofit/pull/461.  Though I've never had any issues with memory in the LUT step, I'm curious if there is some data being copied for each core and if a similar fix (data stored in ray memory with `ray.put` calls) could be done with analytical inversions?

**Comment by pgbrodrick** [comment]
The combination of the recent refactor and the updates to ray 2.9+ seem to have changed the way memory is managed internally.  We're investigating how best to handle that; it definitely has to do with putting the right objects into shared memory, but the specific combination is still up in the air.  If you have specific suggestions, happy to hear them - but a solution to this is definitely in the works.
