### ISSUE TITLE
missing example data

### ISSUE THREAD

**Issue by oskjennifer** [isofit/isofit#614]
we just did a fresh install on a new system and followed the recommended method here: https://isofit.readthedocs.io/en/latest/custom/installation.html#conda-forge-recommended
we then downloaded the additional files/data and built following these instructions:
https://isofit.readthedocs.io/en/latest/custom/data.html

I'm trying to run the default.sh in the small image_cube example. (side note: I had to change the paths in surface.json for the wavelength file and surface.mat which are in the 'data' directory not the 'remote' directory). I ran into this error which maybe can be avoided with the initial package downloads

```
(isofit_env) ubuntu@ip-****:~/.isofit/examples/image_cube/small$ ./default.sh 
2024-12-18 22:17:10,476 ERROR services.py:1350 -- Failed to start the dashboard , return code -11
2024-12-18 22:17:10,476 ERROR services.py:1375 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure' to find where the log file is.
2024-12-18 22:17:10,477 ERROR services.py:1419 -- 
The last 20 lines of /tmp/ray/session_2024-12-18_22-17-09_439737_173414/logs/dashboard.log (it contains the error message from the dashboard): 
2024-12-18 22:17:10,320 INFO head.py:215 -- Starting dashboard metrics server on port 44227
2024-12-18 22:17:10,618 INFO worker.py:1786 -- Started a local Ray instance.
(raylet) The node with node id: 9a2235f3843a2848ac1678877764288b98dd6551c1cf269dc26ec1fd and address: 10.0.3.34 and node name: 10.0.3.34 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a         (1) raylet crashes unexpectedly (OOM, etc.) 
        (2) raylet has lagging heartbeats due to slow network or busy workload.
(raylet) [2024-12-18 22:17:11,223 E 173606 173665] (raylet) agent_manager.cc:83: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent/424238335.
(raylet) The raylet fate shares with the agent. This can happen because
(raylet) - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
(raylet) - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure.
(raylet) - The agent is killed by the OS (e.g., out of memory).
0 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
1 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
2 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
3 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
4 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
5 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
6 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
7 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
2024-12-18 22:17:12,370 INFO worker.py:1619 -- Calling ray.init() again after it has already been called.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/isofit_env/bin/isofit", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/utils/apply_oe.py", line 102, in cli_apply_oe
    apply_oe(SimpleNamespace(**kwargs))
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/utils/apply_oe.py", line 525, in apply_oe
    retrieval_h2o.run()
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/core/isofit.py", line 114, in run
    self.fm = fm = ForwardModel(self.config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/core/forward.py", line 74, in __init__
    self.RT = RadiativeTransfer(self.full_config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/radiative_transfer/radiative_transfer.py", line 93, in __init__
    rte = Engines[confRT.engine_name](**params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/radiative_transfer/radiative_transfer_engine.py", line 227, in __init__
    self.runSimulations()
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/radiative_transfer/radiative_transfer_engine.py", line 431, in runSimulations
    pre = self.preSim()
          ^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/radiative_transfer/engines/sRTMnet.py", line 125, in preSim
    sim = SixSRT(
          ^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/radiative_transfer/engines/six_s.py", line 88, in __init__
    super().__init__(engine_config, **kwargs)
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/radiative_transfer/radiative_transfer_engine.py", line 227, in __init__
    self.runSimulations()
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/radiative_transfer/radiative_transfer_engine.py", line 445, in runSimulations
    lut_names = ray.put(self.lut_names)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/worker.py", line 2772, in put
    object_ref = worker.put_object(value, owner_address=serialize_owner_address)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/worker.py", line 786, in put_object
    self.core_worker.put_serialized_object_and_increment_local_ref(
  File "python/ray/_raylet.pyx", line 3739, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref
  File "python/ray/_raylet.pyx", line 3525, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/includes/common.pxi", line 89, in ray._raylet.check_status
OSError: Broken pipe
```

so then I redownloaded ray from conda-forge: https://docs.ray.io/en/latest/ray-overview/installation.html

now I am getting this error: 
```
(isofit_env) ubuntu@ip-****:~/.isofit/examples/image_cube/small$ ./default.sh 
2024-12-18 22:24:30,280 INFO worker.py:1821 -- Started a local Ray instance.
0 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
1 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
2 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
3 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
4 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
5 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
6 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
7 ['/home/ubuntu/.isofit/data/reflectance/surface_model_ucsb']
2024-12-18 22:24:32,070 INFO worker.py:1654 -- Calling ray.init() again after it has already been called.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/isofit_env/bin/isofit", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/utils/apply_oe.py", line 102, in cli_apply_oe
    apply_oe(SimpleNamespace(**kwargs))
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/utils/apply_oe.py", line 525, in apply_oe
    retrieval_h2o.run()
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/core/isofit.py", line 173, in run
    res = list(
          ^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/util/actor_pool.py", line 170, in get_generator
    yield self.get_next_unordered()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/util/actor_pool.py", line 370, in get_next_unordered
    return ray.get(future)
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::Worker.run_set_of_spectra() (pid=174943, ip=10.0.3.34, actor_id=9b746cffe0eb33bb78e0055001000000, repr=<isofit.core.isofit.Worker object at 0x7ce124382660>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/core/isofit.py", line 242, in run_set_of_spectra
    states = self.iv.invert(input_data.meas, input_data.geom)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/inversion/inverse.py", line 379, in invert
    Seps_inv, Seps_inv_sqrt = self.calc_Seps(x, meas, geom)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/inversion/inverse.py", line 222, in calc_Seps
    return svd_inv_sqrt(
           ^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/isofit/core/common.py", line 303, in svd_inv_sqrt
    D, P = scipy.linalg.eigh(C)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/scipy/linalg/_decomp.py", line 458, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/scipy/_lib/_util.py", line 321, in _asarray_validated
    a = toarray(a)
        ^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/isofit_env/lib/python3.12/site-packages/numpy/lib/function_base.py", line 630, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1734560674.418671  174676 chttp2_transport.cc:1161] ipv4:10.0.3.34:57172: Got goaway [2] err=UNAVAILABLE:GOAWAY received; Error code: 2; Debug Text: Cancelling all calls {created_time:"2024-12-18T22:24:34.418636132+00:00", http2_error:2, grpc_status:14}
```

Here is the logfile output
```
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | namespace(surface_path='/home/ubuntu/.isofit/examples/image_cube/small/configs/surface.json', emulator_base='/home/ubuntu/.is
ofit/srtmnet/sRTMnet_v120.h5', n_cores=4, presolve=True, segmentation_size=400, pressure_elevation=True, log_file='/home/ubuntu/.isofit/examples/image_cube/small/log.txt', input_
radiance='/home/ubuntu/.isofit/imagecube/small/ang20170323t202244_rdn_7000-7010', input_loc='/home/ubuntu/.isofit/imagecube/small/ang20170323t202244_loc_7000-7010', input_obs='/h
ome/ubuntu/.isofit/imagecube/small/ang20170323t202244_obs_7000-7010', working_directory='/home/ubuntu/.isofit/examples/image_cube/small', sensor='ang', copy_input_files=False, mo
dtran_path=None, wavelength_path=None, surface_category='multicomponent_surface', aerosol_climatology_path=None, rdn_factors_path=None, atmosphere_type='ATM_MIDLAT_SUMMER', chann
elized_uncertainty_path=None, model_discrepancy_path=None, lut_config_file=None, multiple_restarts=False, logging_level='INFO', num_cpus=1, memory_gb=-1, empirical_line=False, an
alytical_line=False, ray_temp_dir='/tmp/ray', num_neighbors=(), atm_sigma=(2.0,), prebuilt_lut=None, inversion_windows=(), no_min_lut_spacing=False)
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | Checking input data files...
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | ...Data file checks complete
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | Setting up files and directories....
INFO:2024-12-18,22:36:25 || template_construction.py:__init__() | Flightline ID: ang20170323t202244
INFO:2024-12-18,22:36:25 || template_construction.py:__init__() | no noise path found, proceeding without
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | ...file/directory setup complete
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | Using inversion windows: [[350.0, 1360.0], [1410, 1800.0], [1970.0, 2500.0]]
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | No wavelength file provided. Obtaining wavelength grid from ENVI header of radiance cube.
INFO:2024-12-18,22:36:25 || apply_oe.py:apply_oe() | Wavelength units of nm inferred...converting to microns
INFO:2024-12-18,22:36:25 || template_construction.py:check_surface_model() | No surface model provided. Build new one using given config file.
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | Observation means:
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | Path (km): 20.716992087408016
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | To-sensor azimuth (deg): 71.27130737250893
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | To-sensor zenith (deg): 17.34528282852098
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | To-sun azimuth (deg): 197.3237574125862
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | To-sun zenith (deg): 32.45698605676816
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | Relative to-sun azimuth (deg): 126.05245004007726
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | Altitude (km): 19.808562728369008
INFO:2024-12-18,22:36:26 || apply_oe.py:apply_oe() | Existing h2o-presolve solutions found, using those.
```

Any idea how to resolve it?

**Comment by pgbrodrick** [comment]
The team believes this has been resolved with new updates to both the data package and isofit, but if if that's not the case, please re-open!
